# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Run Karate API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and run Karate tests with Maven
        run: mvn clean test -Dtest=E2ERunner

      - name: Upload Karate HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: target/cucumber-reports

 # deploy-gh-pages:
  #  needs: karate-tests
  #  runs-on: ubuntu-latest
  #  if: github.ref == 'refs/heads/main'

  #  steps:
    #  - name: Checkout repository
   #     uses: actions/checkout@v3

    #  - name: Download artifact
     #   uses: actions/download-artifact@v4
      #  with:
       #   name: karate-reports
        #  path: karate-report

     # - name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
       # with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
         # publish_dir: karate-report
